# Generated by Django 5.0.1 on 2024-02-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_lines',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='mobile',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address_line_1',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address_line_2',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='first_name',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='last_name',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(default='1', max_length=15),
        ),
    ]
