# Generated by Django 5.0.1 on 2024-02-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_alter_shippingaddress_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
