# Generated by Django 5.0.1 on 2024-02-28 08:51

import django.core.validators
import user_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discounted_price',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minimum_amount',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(max_length=15, validators=[user_auth.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[user_auth.models.validate_pin_code]),
        ),
    ]
