# Generated by Django 5.0.1 on 2024-02-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='variation',
            name='stock',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
