# Generated by Django 5.0.1 on 2024-02-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_product_stock_variation_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
