# Generated by Django 5.0.1 on 2024-02-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_product_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discounted_price',
        ),
    ]
