# Generated by Django 5.0.1 on 2024-01-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_product_price_alter_product_stock'),
        ('shop', '0002_rename_products_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='home.variation'),
        ),
    ]
