# Generated by Django 5.0.1 on 2024-02-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='variations',
        ),
    ]
