# Generated by Django 5.0.1 on 2024-01-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_address_line_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=10)),
                ('is_expired', models.BooleanField(default=False)),
                ('discounted_price', models.IntegerField(default=10)),
                ('minimum_amount', models.IntegerField(default=100)),
            ],
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='Variation',
            new_name='variation',
        ),
    ]
