# Generated by Django 5.0.1 on 2024-02-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
