# Generated by Django 5.0.1 on 2024-02-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_wallettransaction_updated_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='updated_balance',
            field=models.PositiveIntegerField(),
        ),
    ]
