# Generated by Django 5.0.1 on 2024-02-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_wallettransaction_updated_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='updated_balance',
            field=models.FloatField(),
        ),
    ]
