# Generated by Django 5.0.1 on 2024-02-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_coupon_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
    ]
