# Generated by Django 5.0.1 on 2024-02-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_remove_coupon_user'),
        ('shop', '0008_alter_cart_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
