# Generated by Django 5.0.1 on 2024-02-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_remove_offer_products_offer_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='valid_to',
            field=models.DateField(),
        ),
    ]
