# Generated by Django 5.0.1 on 2024-02-18 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_variation_product'),
        ('orders', '0029_alter_offer_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer', to='home.product'),
        ),
    ]
